### ISSUE TITLE
Android App Sample

### ISSUE THREAD

**Issue by hashlin** [saturngod/ucs#4]
Hello bro @saturngod 
I just created an android app, which is something like you showed us demo.
Can I contribute it ?
Here is the link https://github.com/hashlin/UCS-Demo
I would thanks to you so much if you could point my mistakes.
Thank you so much .

**Comment by phohtoo** [comment]
Nice work! And I think it would be easier for @saturngod to advise if you ask specific questions. If possible, could you also release your app with compiled apk file so that end users can download,install, try and give feedback.

**Comment by saturngod** [comment]
thanks. I will put in code folder.

**Comment by hashlin** [comment]
Just did it bro :) @phohtoo 
Thank you bro @saturngod
